### ISSUE TITLE
Stripe Attribute Error

### ISSUE THREAD

**Issue by teaglebuilt** [justdjango/video-membership#1]
When trying to process a fake payment using 42424242.......
I get a success message with the token but then goes to an error page that says
module 'stripe' has no attribute 'CardError'
and the membership does not change in the admin afterwards. 

```

except stripe.CardError as e:
			messages.info(request, "Your card has been declined")

```

**Comment by mattfreire** [comment]
Can you check your stripe version please?

**Comment by teaglebuilt** [comment]
Yes i upgraded and the error still persisted. I had to add the word error below.
except stripe.error.CardError as e:
			messages.info(request, "Your card has been declined"
Your right once i changed the version to yours it changed. Although i still get an error that says source is not a paremeter when creating a subscription. according to the api its not, and this is the same version as yours.

**Comment by mattfreire** [comment]
I can't seem to replicate this error on my side. Are you installing the dependencies using the requirements.txt file in this repo?

**Comment by teaglebuilt** [comment]
2018-07-27
The subscription endpoints no longer support the source parameter. If you want to change the default source for a customer, instead use the source creation API to add the new source and then the customer update API to set it as the default.

So basically now i have to create a source and update a customer? How is your code working according to the updates Stripe has made? I made sure i also had version 1.84 of stripe as well

**Comment by teaglebuilt** [comment]
So what i posted is on the stripe api docs just added. So since there is no source attribute, how would i do it?

**Comment by thinh9e** [comment]
You can try:
```python
if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            cus = stripe.Customer.retrieve(user_membership.stripe_customer_id)
            cus.source = token
            cus.save()
            subscription = stripe.Subscription.create(
                customer=user_membership.stripe_customer_id,
                items=[{
                    'plan': selected_membership.stripe_plan_id
                }]
            )
            return redirect(reverse('memberships:update-transactions', kwargs={
                'sub_id': subscription.id
            }))
        except stripe.error.CardError:
            messages.info(request, 'Your card has been declined')
```

**Comment by mattfreire** [comment]
Pushed a new [commit](https://github.com/justdjango/video-membership/commit/e776b02ce817f1b37a2430034f5bf5944cb34a4b) resolving this issue

**Comment by CNJr11** [comment]
Matt, 

In the 'PaymentView', for some reason my code isn't executing the if conditions and redirecting to the memberships:update-transactions method. Instead it's moving to the except, and returning the message.info. 

Therefore the membership being selected isn't registering for some reason, any help? 

I am using django-admin version 3.0.5. 

CB


![Screen Shot 2020-04-09 at 6 17 29 PM](https://user-images.githubusercontent.com/32998636/78945501-754ac300-7a8e-11ea-8730-b232c6eba59b.png)
