### ISSUE TITLE
request error: no such plans123

### ISSUE THREAD

**Issue by Amitpant945** [justdjango/video-membership#3]
I used same code like yours but on  " request.post['stripeToken'']" , when i use this then it's show me multikey value pair error. so, i used "request.post.get('stripe Token')" then it's show me Request error No such plans 123.
I searched  many time on google but i found nothing regarding this. So, could you please explain me why it's happening and give me fruitful solution for that.
thanks

**Comment by mattfreire** [comment]
This is probably because you did not set up your stripe account.

**Comment by Amitpant945** [comment]
same problem i had found while i was working on my subscription website.
you need to set plans first.
