### ISSUE TITLE
ModuleNotFoundError: No module named 'allauth'

### ISSUE THREAD

**Issue by hvitis** [justdjango/video-membership#5]
Once downloaded the requirements file needs to have a line on the bottom with django all auth installation:

certifi==2018.11.29
chardet==3.0.4
Django==2.1.5
idna==2.7
Pillow==5.3.0
pytz==2018.7
requests==2.20.1
stripe==2.15.0
urllib3==1.24.1
**django-allauth==0.38.0**

**Comment by justdjango** [comment]
This has been added
