### ISSUE TITLE
memberships.models.DoesNotExist: Membership matching query does not exist

### ISSUE THREAD

**Issue by nimzoking** [justdjango/video-membership#6]
1. Downloaded ZIP
2. Created venv with pip -r requirements.txt
3. makemigrations
4. migrate
5. createsuperuser ---> generates error 

memberships.models.DoesNotExist: Membership matching query does not exist

Suspect issue is due to empty DB, and the membership model looking for a lookup of membership type.

**Comment by nimzoking** [comment]
Rolled back to de43c68 and able to get things up and running, not sure if everything is working as such - as some urls error - but that should be straightforward to sort out.

**Comment by UtkuBulkan** [comment]
Still this problem is there. I cannot create the superuser.  Is there any other suggestions to overcome this problem with the latest code?

**Comment by UtkuBulkan** [comment]
In order to create a superuser, comment out the following lines.
Then when you have succesfully created the superuser you can uncomment them back.

```
       if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
       new_customer_id = stripe.Customer.create(email=instance.email)
#      free_membership = Membership.objects.get(membership_type='Free')
       user_membership.stripe_customer_id = new_customer_id['id']>
#      user_membership.membership = free_membership
       user_membership.save()
```

**Comment by prime7** [comment]
Before creating any user/superuser make a Membership object.

- python manage.py shell
- from memberships.models import Membership
- Membership.objects.create(slug="Free",membership_type="Free",price=0,stripe_plan_id="your_plan_id")
